config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :bugs

  root 'bugs#index'

end

app/models/bug.rb
class Bug < ActiveRecord::Base
    belongs_to :user
    validates :title,  presence: true, length: {minimum: 5, maximum: 80}
    validates :despriction, presence: true, length: {minimum: 20, maximum: 600}
    enum status: [:open, :closed, :monitor]
    enum issue_type: [:issue, :enhancement, :feature]
    enum priority: [:low, :medium, :high]
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :bugs
    validates :fname, :lname, :email, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     validates :email, presence: true, length: {maximum: 105},
             uniqueness: { case_sensitive: false },
             format: { with: VALID_EMAIL_REGEX }
     validates :thumbnail, allow_blank: true, format: {with:
     %r{\.(gif|jpg|png)\Z}i,
     message: 'must be a URL for GIF, JPG or PNG image.'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_statuses
  before_action :set_priorities
  before_action :set_issue_types
  before_action :set_bug, only: [:show, :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
        user = User.find(bug_params[:user_id])
        @bug.build_user(:id => user.id)
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end
    def set_statuses
      @statuses = Bug.statuses
    end
    def set_priorities
      @priorities = Bug.priorities
    end
    def set_issue_types
      @issue_types = Bug.issue_types
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :despriction, :issue_type, :priority, :status, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_form.html.erb
<%= form_for(@bug) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :despriction %><br>
    <%= f.text_area :despriction %>
  </div>
  <div class="field">
    <%= f.label :issue_type %><br>
    <%= f.select :issue_type, options_for_select(@issue_types.collect {|s| [s[0].humanize, s[0]]},
     selected: @bug.issue_type), {} %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.select :priority, options_for_select(@priorities.collect {|s| [s[0].humanize, s[0]]},
     selected: @bug.priority), {} %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(@statuses.collect {|s| [s[0].humanize, s[0]]},
     selected: @bug.status), {} %>
  </div>
  <div class="field">
        <%= f.label :user_id %><br>
        <%= f.select :user_id,
            options_for_select(User.all.collect {|u| ["#{u.lname},
            #{u.fname}", u.id]},
            selected: (@bug.user ? @bug.user.id : User.first.id)),
            {} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

<script>
      $(".content").hide();
      $(".bugs").css({"margin-top" : "5%"})
</script>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

<!--<h1>Listing Bugs</h1>-->
<!--Responsive tab starts here...-->
<main class="bugs-index">
  
  <input id="tab1" type="radio" name="tabs" checked>
  <label for="tab1">Open</label>
    
  <input id="tab2" type="radio" name="tabs">
  <label for="tab2">Closed</label>
    
  <input id="tab3" type="radio" name="tabs">
  <label for="tab3">Monitor</label>
    
  <section id="content1">
   
    <table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Despriction</th>
      <th>Issue type</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
    <% if bug.status == "open" %>
      <tr>
        <td><%= (bug.user.try(:lname) || "NA") %></td>
        <td><%= bug.title %></td>
        <td><%= bug.despriction %></td>
        <td><%= bug.issue_type %></td>
        <td><%= bug.priority %></td>
        <td><%= bug.status %></td>
        <td><%= link_to 'Show', bug %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<!--<a onclick="return popitup('/bugs/new')">New Bug</a>-->
 <%= link_to 'New Bug', new_bug_path %>
  </section>
    
  <section id="content2">
       <table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Despriction</th>
      <th>Issue type</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
    <% if bug.status == "closed" %>
      <tr>
        <td><%= (bug.user.try(:lname) || "NA") %></td>
        <td><%= bug.title %></td>
        <td><%= bug.despriction %></td>
        <td><%= bug.issue_type %></td>
        <td><%= bug.priority %></td>
        <td><%= bug.status %></td>
        <td><%= link_to 'Show', bug %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
 <%= link_to 'New Bug', new_bug_path %>
  </section>
    
  <section id="content3">
       <table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Despriction</th>
      <th>Issue type</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
    <% if bug.status == "monitor" %>
      <tr>
        <td><%= (bug.user.try(:lname) || "NA") %></td>
        <td><%= bug.title %></td>
        <td><%= bug.despriction %></td>
        <td><%= bug.issue_type %></td>
        <td><%= bug.priority %></td>
        <td><%= bug.status %></td>
        <td><%= link_to 'Show', bug %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

   <%= link_to 'New Bug', new_bug_path %>

  </section>
    
</main>
<!--Responsive Tab ends here...-->
<!--<script language="javascript" type="text/javascript">-->
<!--
<!--function popitup(url) {-->

<!--	newwindow=window.open(url,'name','height=200,width=150');-->
<!--	if (window.focus) {newwindow.focus()}-->
<!--	return false;-->
<!--}-->

// -->
<!--</script>-->

app/views/bugs/new.html.erb
<div class="fix-position">
    <h1>New Bug</h1>

<%= render 'form' %>

<%= link_to 'Back', bugs_path %>
</div>

<script>
      $(".content").hide();
      $(".bugs").css({"margin-top" : "5%"})
</script>

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bug.title %>
</p>

<p>
  <strong>Despriction:</strong>
  <%= @bug.despriction %>
</p>

<p>
  <strong>Issue type:</strong>
  <%= @bug.issue_type %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @bug.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bug.status %>
</p>
<p>
  <strong>User:</strong>
  <%= (@bug.user.try(:lname) || "NA")%>
</p>
<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>
<script>
      $(".content").hide();
      $(".bugs").css({"margin-top" : "5%"})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body class="<%= controller.controller_name %>">
<div class="content">
    <!--<h1 class="title">BugRoo</h1>-->
			<ul id="sdt_menu" class="sdt_menu">
				<li>
					<a href="#">
						<img src="/assets/2.jpg" alt=""/>
						<span class="sdt_active"></span>
						<span class="sdt_wrap">
							<span class="sdt_link">Bugs</span>
							<!--<span class="sdt_descr">Get to know me</span>-->
						</span>
					</a>
				 <div class="sdt_box">
							<a href="bugs/new">Create</a>
							<a href="#" onclick="alertSelect()">Edit</a>
					</div>
				</li>
				<li>
					<a href="#">
						<img src="/assets/1.jpg" alt=""/>
						<span class="sdt_active"></span>
						<span class="sdt_wrap">
							<span class="sdt_link">Users</span>
							<!--<span class="sdt_descr">My work</span>-->
						</span>
					</a>
					<div class="sdt_box">
							<a href="users/new">Create</a>
							<a href="#" onclick="alertSelect()">Edit</a>
					</div>
				</li>
				<li>
					<a href="#" onclick="underContruction()">
						<img src="/assets/3.jpg" alt=""/>
						<span class="sdt_active"></span>
						<span class="sdt_wrap">
							<span class="sdt_link" onclick="underContruction()">History</span>
							<!--<span class="sdt_descr">Where ideas get born</span>-->
						</span>
					</a>
				</li>
				<li>
					<a href="#" onclick="underContruction()">
						<img src="/assets/4.jpg" alt=""/>
						<span class="sdt_active"></span>
						<span class="sdt_wrap">
							<span class="sdt_link" onclick="underContruction()">Open Bugs</span>
							<!--<span class="sdt_descr">I like to photograph</span>-->
						</span>
					</a>
				</li>
				<li>
					<a href="#" onclick="underContruction()">
						<img src="/assets/5.jpg" alt=""/>
						<span class="sdt_active"></span>
						<span class="sdt_wrap">
							<span class="sdt_link" onclick="underContruction()">Priority</span>
							<!--<span class="sdt_descr">I write about design</span>-->
						</span>
					</a>
				</li>
				<li>
					<a href="#" onclick="underContruction()">
						<img src="/assets/6.jpg" alt=""/>
						<span class="sdt_active"></span>
						<span class="sdt_wrap">
							<span class="sdt_link" onclick="underContruction()">Analysis</span>
							<!--<span class="sdt_descr">I like to code</span>-->
						</span>
					</a>
					<div class="sdt_box">
						<a href="#" onclick="underContruction()">Bugs</a>
						<a href="#" onclick="underContruction()">Users</a>
					</div>
				</li>
			</ul>
		</div>
<!--<div class="background-img">-->
	
<!--</div>-->
	<div class="body-div">

   <%= yield %>
		</div>
</body>
</html>
<script>
	$(document).ready(function(){
/**
				* for each menu element, on mouseenter, 
				* we enlarge the image, and show both sdt_active span and 
				* sdt_wrap span. If the element has a sub menu (sdt_box),
				* then we slide it - if the element is the last one in the menu
				* we slide it to the left, otherwise to the right
				*/
                $('#sdt_menu > li').bind('mouseenter',function(){
					var $elem = $(this);
					$elem.find('img')
						 .stop(true)
						 .animate({
							'width':'170px',
							'height':'170px',
							'left':'0px'
						 },400,'easeOutBack')
						 .andSelf()
						 .find('.sdt_wrap')
					     .stop(true)
						 .animate({'top':'140px'},500,'easeOutBack')
						 .andSelf()
						 .find('.sdt_active')
					     .stop(true)
						 .animate({'height':'170px'},300,function(){
						var $sub_menu = $elem.find('.sdt_box');
						if($sub_menu.length){
							var left = '170px';
							if($elem.parent().children().length == $elem.index()+1)
								left = '-170px';
							$sub_menu.show().animate({'left':left},200);
						}	
					});
				}).bind('mouseleave',function(){
					var $elem = $(this);
					var $sub_menu = $elem.find('.sdt_box');
					if($sub_menu.length)
						$sub_menu.hide().css('left','0px');
					
					$elem.find('.sdt_active')
						 .stop(true)
						 .animate({'height':'0px'},300)
						 .andSelf().find('img')
						 .stop(true)
						 .animate({
							'width':'0px',
							'height':'0px',
							'left':'85px'},400)
						 .andSelf()
						 .find('.sdt_wrap')
						 .stop(true)
						 .animate({'top':'25px'},500);
				});
				
			
});
	function alertSelect(){
					alert("Please select the record from table below");
				}
	function underContruction(){
		alert("OOPS! Krishna is working on it.");
	}
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<script>
      $(".content").hide();
      $(".users").css({"margin-top" : "5%"});
</script>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<main class="bugs-index">
<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= user.thumbnail %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

<script>
      $(".content").hide();
      $(".users").css({"margin-top" : "5%"})
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @user.thumbnail %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<script>
      $(".content").hide();
      $(".users").css({"margin-top" : "5%"});
</script>